name: HTML CI Pipeline

on:
  push:
    branches: ["master"]

jobs:
  test_html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files in project
        run: ls -R

      - name: Print success message
        run: echo "HTML CI pipeline ran successfully for Safee!"
